name: CI/CD

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  packages: write
  statuses: write
   
jobs:
  buildAndPublish:
    name: Build (and publish) to NPM (GH)
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: yarn
          registry-url: https://npm.pkg.github.com
      - name: Enable yarn berry
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run build
        run: yarn build
      - name: Publish package
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify Google Chat
        uses: evidenceprime/google-chat-notifications@master
        if: ${{ always() && github.event_name == 'push' }}
        with:
          title: Convict
          subtitle: ${{ github.event.head_commit.message }}
          webhookUrl: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
          threadKey: <thread-key>
          status: ${{ job.status }}
